name: time_remaining
description: time_remaining tells you in the form of a countdown the exact time remaining until the time you want is fulfilled.
version: 1.0.2
homepage: https://github.com/lrferreiro/time_remaining

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter